image: python:3.10

stages:
  - test

pytest:
  stage: test
  before_script: []
  script:
    - pip install poetry
    - poetry run coverage run -m pytest
    - poetry run coverage report
    - poetry run coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
