version: '3.10'

services:

  postgres-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - src/.env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - djangonetwork

  web:
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - src/.env.dev
    depends_on:
      - postgres-db
    networks:
      - djangonetwork

networks:
    djangonetwork:
        driver: bridge
