# Generated by Django 4.0.5 on 2022-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_note_categories_delete_notecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.CharField(default='gg', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
