# Generated by Django 4.0.5 on 2022-06-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='logic.category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
