# Generated by Django 4.0.5 on 2022-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_note_categories_alter_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
