# Generated by Django 4.0.5 on 2022-06-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_note_user_delete_usernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notecategory',
            name='note',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteCategory',
        ),
    ]
