FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install poetry==1.1.13
COPY poetry.lock pyproject.toml /app/
RUN poetry install

COPY . .

EXPOSE 8000

WORKDIR /app/src

CMD poetry run python3 manage.py migrate && poetry run python3 manage.py runserver 0.0.0.0:8000
